name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cutover-mcp-test .

      - name: Run tests with coverage in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            cutover-mcp-test \
            bash -c "uv pip install --system -e '.[dev]' && pytest --cov=cutover_mcp --cov-report=xml --cov-report=html --cov-report=term-missing -v"

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 7
